Description: |
  Iyanuoluwa Solomon Udacity Project 2 | 2022
  
Parameters:
  #Parameters needed for Udagram project
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: xxx
  # S3BucketName:
  #   Description: >
  #     A globally unique S3 bucket name. 
  #     Please upload the src.zip to the bucket after creating this stack.
  #   Type: String
  #   Default: udagram-0676982224131
  # KeyPair:
  #   Description: The keypair to use for your instances
  #   Type: String
  #   Default: keypair
  AMIToUse:
    Description: The AMI to use for your instances (I am working in us-west-2)
    Type: String
    Default: ami-005de95e8ff495156

Resources:
  # SERVER RESOURCES
  LoadBalancerSecGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http traffic to and from load balancer
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServerSecGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh to our load balancer
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # change to your IP later
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  # S3Buckets:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     AccessControl: PublicRead
  #     BucketName: !Ref S3BucketName
  #     MetricsConfigurations:
  #       - Id: EntireBucket
  #     WebsiteConfiguration:
  #       IndexDocument: index.html
  #       ErrorDocument: error.html
  WebAppLaunchConfigs:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          aws s3 cp s3://udagram-0676982224131/src.zip .
          unzip -o src.zip
      ImageId: !Ref AMIToUse
     # KeyName: !Ref KeyPair
      IamInstanceProfile: !Ref ProfileWithRolesForOurApps
      SecurityGroups:
        - Ref: WebServerSecGroups
      InstanceType: t3.medium
      BlockDeviceMappings:
        - DeviceName: '/dev/sdk'
          Ebs:
            VolumeSize: '10'
  WebAppGroups:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub '${EnvironmentName}-PRIV-NETS'
      LaunchConfigurationName:
        Ref: WebAppLaunchConfigs
      MinSize: '4'
      MaxSize: '5'
      TargetGroupARNs:
        - Ref: WebAppTargetGroups
  WebAppTargetGroups:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'
  WebAppLBs:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
        - Ref: LoadBalancerSecGroups
      Subnets:
        - Fn::ImportValue: !Sub '${EnvironmentName}-PUB1-SN'
        - Fn::ImportValue: !Sub '${EnvironmentName}-PUB2-SN'
  Listeners:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebAppTargetGroups
      LoadBalancerArn:
        Ref: WebAppLBs
      Port: 80
      Protocol: HTTP
  ALBListenerRules:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref 'WebAppTargetGroups'
      Conditions:
        - Field: path-pattern
          Values: [/]
      ListenerArn: !Ref 'Listeners'
      Priority: 1
  BastionServers:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIToUse
    #  KeyName: !Ref KeyPair
      InstanceType: t3.medium
      Tags:
        - Key: Name
          Value: Bastion Server
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - Ref: WebServerSecGroups
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: '${EnvironmentName}-BAST-SN'
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
  S3ReadOnlyEC2s:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
  RolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AmazonS3ReadOnlyAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:Put*
              - s3:Get*
              - s3:List*
            Resource:
              - arn:aws:s3:::udagram-0676982224131/
              - arn:aws:s3:::udagram-0676982224131/*
      Roles:
        - Ref: S3ReadOnlyEC2s
  ProfileWithRolesForOurApps:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - Ref: S3ReadOnlyEC2s

Outputs:
  WebAppLoadBalancerDNSNames:
    Description: DNS name or Public URL of the Load Balancer
    Value: !Join ['', ['http://', !GetAtt WebAppLBs.DNSName]]
    Export:
      Name: !Sub ${EnvironmentName}-LB-DNSName
